      - name: Run code with coverage
        run: julia --project=. -e '
          using Coverage;
          include("run_ue.jl");
          Coverage.process_folder("."); 
          Coverage.LCOV.writefile("coverage/lcov.info", Coverage.process_folder("."))
        '

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: false
